# Override http_archive for local testing
local_repository(
    name = "rules_qt",
    path = "../..",
)

# (copied from https://github.com/tensorflow/tensorflow/blob/58e320bee974240b4193ffe7da7bc1cc1c43a551/WORKSPACE#L5)
# The cascade of load() statements and rules_qt_dependencies?() calls works around the
# restriction that load() statements need to be at the top of .bzl files.
# E.g. we can not retrieve a new repository with http_archive and then load()
# a macro from that repository in the same file.

load("@rules_qt//qt:repositories.bzl", "rules_qt_dependencies")

rules_qt_dependencies(qt_version = "6.2.4")

load("@rules_qt//qt:repositories2.bzl", "rules_qt_dependencies2")

rules_qt_dependencies2()

load("@rules_qt//qt:repositories3.bzl", "rules_qt_dependencies3")

rules_qt_dependencies3()

load("@rules_qt//qt:repositories4.bzl", "rules_qt_dependencies4")

rules_qt_dependencies4()
