# Override http_archive for local testing
local_repository(
    name = "rules_qt",
    path = "../..",
)

load("@rules_qt//qt:repositories.bzl", "rules_qt_dependencies")

rules_qt_dependencies(qt_version = "6.2.4")

load("@rules_qt//qt:repositories_extra.bzl", "rules_qt_extra_dependencies")

rules_qt_extra_dependencies()

load("@rules_qt//qt:repositories_extra_extra.bzl", "rules_qt_extra_extra_dependencies")

rules_qt_extra_extra_dependencies()
