# Override http_archive for local testing
local_repository(
    name = "rules_qt",
    path = "../..",
)

load("@rules_qt//qt:repositories.bzl", "rules_qt_dependencies")

rules_qt_dependencies(qt_version = "6.2.4")

load("@rules_qt//qt:repositories2.bzl", "rules_qt_dependencies2")

rules_qt_dependencies2()

load("@rules_qt//qt:repositories3.bzl", "rules_qt_dependencies3")

rules_qt_dependencies3()

load("@rules_qt//qt:repositories4.bzl", "rules_qt_dependencies4")

rules_qt_dependencies4()
